from pyspark.sql.types import (
    ArrayType, BooleanType, DateType, DecimalType,
    IntegerType, FloatType, LongType, StringType,
    StructType, StructField, TimestampType
)


VITALS = """
    client_id           String,
    patient_id          String,
    service_date        String,
    service_time        String,
    height_cm           String,
    height_in           String,
    height_comment      String,
    weight_kg           String,
    weight_lbs          String,
    weight_comment      String,
    temperature_c       String,
    temperature_f       String,
    temperature_comment String,
    pulse               String,
    pulse_comment       String,
    respiration         String,
    respiration_comment String,
    bp_systolic         String,
    bp_diastolic        String,
    bp_comment          String,
    oxygen_saturation   String,
    oxygen_comment      String,
    bmi                 String,
    bmi_comment         String,
    clinician           String,
    encounter_id        String,
    comment             String,
    hj_create_timestamp String,
    hj_modify_timestamp String,
    client_vitals_id    String,
    row_hash            String
"""

CQ_VITALS = StructType([
    # StructField('id', LongType(), nullable=True),
    StructField('client_id', StringType(), nullable=True),
    StructField('source_ale_prac_id', LongType(), nullable=True),
    StructField('encounter_id', StringType(), nullable=True),
    StructField('patient_id', StringType(), nullable=True),
    # StructField('pt_id', LongType(), nullable=True),
    StructField('name', StringType(), nullable=True),
    StructField('code', StringType(), nullable=True),
    StructField('code_system_name', StringType(), nullable=True),
    StructField('code_system_oid', StringType(), nullable=True),
    # StructField('orig_code', StringType(), nullable=True),
    # StructField('orig_code_system_name', StringType(), nullable=True),
    StructField('value', StringType(), nullable=True),
    StructField('unit', StringType(), nullable=True),
    # StructField('status', StringType(), nullable=True),
    StructField('observation_date', TimestampType(), nullable=True),
    # StructField('cq_document_id', LongType(), nullable=True),
    # StructField('content_lineage_id', LongType(), nullable=True),
    # StructField('source_name', StringType(), nullable=True),
    StructField('source_guid', StringType(), nullable=True),
    # StructField('created_at', TimestampType(), nullable=True),
    # StructField('updated_at', TimestampType(), nullable=True),
])
