version: "3.8"
services:
  stage_data:
    image: stage_data
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4040:4040
    command: [
      "/bin/sh",
      "-c",
      "/opt/spark/bin/spark-submit \
      --name stage_data \
      local:///opt/spark/stage_data/main.py \
      --filepath s3a://bangkok/departuredelays.csv
      --output_path s3a://condesa/departuredelays"
    ]
    env_file: .env
    environment:
      - LOG_LEVEL=WARN
    volumes:
      - ./local_config:/opt/spark/conf
      # - ./local_hive:/opt/spark/hive_warehouse
      - ./sample_data/synthea_1m_fhir_3_0_May_24/output_1/csv:/opt/spark/work-dir/sample_data/output_1
      - ./sample_data/synthea_1m_fhir_3_0_May_24/output_2/csv:/opt/spark/work-dir/sample_data/output_2
      - ./sample_data/output_data:/opt/spark/work-dir/output_data
