# Standard spark 3.1.1 base container with Python bindings
# Usage: docker build -t spark-ingest:latest --no-cache .
ARG spark_image=spark-py:3.1.1-3.2
FROM ${spark_image}

# Reset to root to run installation tasks
USER 0

ENV APP_HOME=${SPARK_HOME}/jupyter-lib
ENV PATH=$PATH:${APP_HOME}

RUN adduser --shell /bin/bash --system --home ${APP_HOME} jupyter-lib

COPY requirements.txt ${APP_HOME}/requirements.txt

RUN pip install --upgrade pip wheel setuptools \
    && pip --no-cache-dir install -r ${APP_HOME}/requirements.txt \
    && rm /${APP_HOME}/requirements.txt

# COPY --chown=jupyter-lib:jupyter-lib ./notebooks ${APP_HOME}/notebooks
ENV PYTHONPATH=${APP_HOME}

WORKDIR ${APP_HOME}
# ENTRYPOINT [ "/opt/entrypoint.sh" ]

# Specify the User that the actual main process will run as
# ARG spark_uid=185
# USER ${spark_uid}
USER jupyter-lib

WORKDIR ${APP_HOME}
# CMD "jupyter notebook --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"